version: '3.9'

services:
  postgres_db:
    image: postgis/postgis:latest
    restart: always
    hostname: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: places_remember_user
      POSTGRES_DB: places_remember_db

  django:
    build:
      context: ./places_remember_back
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    volumes:
      - .:/usr/src/places_remember
    command: >
      sh -c   "
              python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              coverage run manage.py test &&
              coverage report &&
              python3 manage.py runserver 0.0.0.0:8000
              "
    ports:
      - 8000:8000

volumes:
  postgres: