version: '2.1'

services:
  postgres:
    restart: unless-stopped
    image: postgis/postgis:latest

    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: places_remember_user
  django:
    build:
      context: ./places_remember_back
      dockerfile: Dockerfile
    command: >
      sh -c   "python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              coverage run manage.py test &&
              coverage report &&
              python3 manage.py runserver 0.0.0.0:8000
             "
    volumes:
      - .:/usr/src/places_remember
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres: