name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:latest
        env:
          POSTGRES_PASSWORD: 123
          POSTGRES_USER: places_remember_user
          POSTGRES_DB: places_remember_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd places_remember_back/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        sudo apt install libgdal-dev
        cd places_remember_back/
        python manage.py makemigrations
        python manage.py migrate
        coverage run manage.py test
        coverage report
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}