name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up --build

  linter:

    runs-on: ubuntu-latest

    steps:
      - name: Lint Code Base
      - uses: actions/checkout@v3
      - uses: docker://github/super-linter:v2.1.0
